version: '3'
services:
  auth_db:
    image: postgres:11
    environment:
      POSTGRES_DB: accountservices
      POSTGRES_PASSWORD: dev-password
  auth_service:
    build: ${AUTH_DIR:-.}
    command: flask run -h 0.0.0.0
    env_file:
      - ${AUTH_DIR:-.}/.env
    environment:
      PGDATABASE: accountservices
      PGUSER: postgres
      PGHOST: auth_db
      FLASK_APP: run.py
      FLASK_ENV: development
      SECRET_KEY: local-dev-db
      SQLALCHEMY_DATABASE_URI: "postgresql://postgres:dev-password@auth_db/accountservices"
      EMAIL_DRIVER: sendgrid
      SYSTEM_EMAIL: 
      SENDGRID_API_KEY: 
      SENDGRID_PASSWORD_RESET_TEMPLATE_ID: 
    volumes:
      - ${AUTH_DIR:-.}:/opt/app:delegated
    ports:
      - "${AUTH_PORT:-5000}:5000"
    depends_on:
      - auth_db
