version: '3'
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_DB: workflowservice
      POSTGRES_PASSWORD: dev-password
  storage:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio123
    volumes:
      - ./uploads:/data:delegated
    ports:
      - "9000:9000"
  api:
    build: .
    image: openfido/openfido-app-service
    command: flask run -h 0.0.0.0
    environment:
      PGDATABASE: workflowservice
      PGUSER: postgres
      PGHOST: db
      FLASK_APP: run.py
      FLASK_ENV: development
      SECRET_KEY: local-dev-db
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:dev-password@db/workflowservice
      S3_ACCESS_KEY_ID: minio_access_key
      S3_SECRET_ACCESS_KEY: minio123
      S3_ENDPOINT_URL: http://storage:9000
    volumes:
      - .:/opt/app:delegated
    ports:
      - "5000:5000"
    depends_on:
      - db
      - storage
