version: '3'
services:
  queue:
    image: rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_USER: rabbit-user
      RABBITMQ_DEFAULT_PASS: rabbit-password
      RABBITMQ_DEFAULT_VHOST: api-queue
  db:
    image: postgres:11
    environment:
      POSTGRES_DB: workflowservice
      POSTGRES_PASSWORD: dev-password
  storage:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - ./uploads:/data:delegated
  api:
    build: .
    image: presencepg/presence-workflow
    command: flask run -h 0.0.0.0
    environment:
      PGDATABASE: workflowservice
      PGUSER: postgres
      PGHOST: db
      FLASK_APP: run.py
      FLASK_ENV: development
      SECRET_KEY: local-dev-db
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:dev-password@db/workflowservice
      CELERY_RESULT_BACKEND: amqp://rabbit-user:rabbit-password@queue/api-queue
      CELERY_BROKER_URL: amqp://rabbit-user:rabbit-password@queue/api-queue
      S3_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      S3_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      S3_ENDPOINT_URL: http://storage:9000
    volumes:
      - .:/opt/app:delegated
    ports:
      - "5000:5000"
    depends_on:
      - db
      - queue
      - storage
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: presencepg/presence-workflow-worker
    command: celery -A app.worker worker -l DEBUG
    environment:
      CELERY_RESULT_BACKEND: amqp://rabbit-user:rabbit-password@queue/api-queue
      CELERY_BROKER_URL: amqp://rabbit-user:rabbit-password@queue/api-queue
      WORKER_API_SERVER: http://api:5000
      S3_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      S3_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      S3_ENDPOINT_URL: http://storage:9000
    env_file:
      - .worker-env
    volumes:
      - .:/opt/app:delegated
      - /var/run/docker.sock:/var/run/docker.sock
      # The 'docker in docker' nature of this local configuration means that
      # bind mounts happen on the 'host docker' not the first docker container.
      # Make temp directories on the main host (otherwise files cannot be
      # found).
      - /tmp:/tmp
    depends_on:
      - queue
      - api
      - storage
