version: '3'
services:
  app_db:
    image: postgres:11
    environment:
      POSTGRES_DB: appservice
      POSTGRES_PASSWORD: dev-password
  app_service:
    build: ${APP_DIR:-.}
    command: flask run -h 0.0.0.0
    environment:
      PGDATABASE: appservice
      PGUSER: postgres
      PGHOST: app_db
      FLASK_APP: run.py
      FLASK_ENV: development
      SECRET_KEY: local-dev-db
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:dev-password@app_db/appservice
      S3_ACCESS_KEY_ID: minio_access_key
      S3_SECRET_ACCESS_KEY: minio123
      S3_ENDPOINT_URL: http://workflow_storage:9000
      AUTH_HOSTNAME: http://auth_web:5000
      WORKFLOW_HOSTNAME: http://workflow_service:5000
    volumes:
      - ${APP_DIR:-.}:/opt/app:delegated
    ports:
      - "${APP_PORT:-5000}:5000"
    depends_on:
      - app_db
      - workflow_storage
      - auth_web
      - workflow_service
