version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: pip install -r platform/requirements.txt
      - run: 
          name: Run Unit Tests
          command: echo "Will eventually run unit tests"
          
  deploy:
    docker:
      - image: circleci/python:3.8

    steps:
      - run: |
          echo 'run terraform to deploy this out when ready'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
