version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.14.0
  aws-ecs: circleci/aws-ecs@1.4.0
jobs:
  test:
    docker:
      - image: python:3.8
    environment:
      PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/my-project
    steps:
      - checkout
      - run:
          command: |
            apt-get update -qq
            apt-get install -y pipenv
            pip install virtualenv
      - restore_cache:
          keys:
            - project-pipfile-{{ checksum "Pipfile.lock" }}
      - run:
          command: pipenv install --dev --deploy
      - save_cache:
          key: project-pipfile-{{ checksum "Pipfile.lock" }}
          paths:
            - .venv
      - run:
          command: |
            mkdir test-results
            pipenv run invoke test --junit --enforce-percent 100
      - store_test_results:
          path: test-results
      - run:
          command: pipenv run invoke style
      - run:
          command: pipenv run invoke lint --fail-under=9
  build-docker:
    docker:
      - image: circleci/python:3.8
    environment:
      DOCKER_BUILDKIT: "1"
    parameters:
      access-key:
        type: env_var_name
        default: AWS_ACCESS_KEY_ID
      secret-key:
        type: env_var_name
        default: AWS_SECRET_ACCESS_KEY
      ecr-url:
        type: env_var_name
        default: AWS_ECR_ACCOUNT_URL
    steps:
      - setup_remote_docker:
          version: 18.09.3
      - aws-ecr/build-and-push-image:
          tag: "master"
          repo: openfido/dev-app
          extra-build-args: "--ssh default"
          account-url: << parameters.ecr-url >>
          aws-access-key-id: << parameters.access-key >>
          aws-secret-access-key: << parameters.secret-key >>
workflows:
  pullrequests:
    jobs:
      - test:
          filters:
            branches:
              ignore: /master/
  dev:
    jobs:
      - test:
          filters:
            branches:
              only: /master/
      - build-docker:
          requires:
            - test
          filters:
            branches:
              only: /master/
          access-key: AWS_ACCESS_KEY_ID
          secret-key: AWS_SECRET_ACCESS_KEY
          ecr-url: AWS_ECR_ACCOUNT_URL
      - aws-ecs/deploy-service-update:
          requires:
            - build-docker
          filters:
            branches:
              only: /master/
          family: 'openfido-dev-app-task'
          cluster-name: 'openfido-dev-ecs-cluster'
          service-name: 'openfido-dev-app-service'
          container-image-name-updates: 'container=openfido-dev-app-task,tag=master'

  prod:
    jobs:
      - test:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)+/
            branches:
              ignore: /.*/
      - build-docker:
          requires:
            - test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)+/
            branches:
              ignore: /.*/
          access-key: PROD_AWS_ACCESS_KEY_ID
          secret-key: PROD_AWS_SECRET_ACCESS_KEY
          ecr-url: PROD_AWS_ECR_ACCOUNT_URL
      - aws-ecs/deploy-service-update:
          requires:
            - build-docker
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)+/
            branches:
              ignore: /.*/
          family: 'openfido-dev-app-task'
          cluster-name: 'openfido-prod-ecs-cluster'
          service-name: 'openfido-prod-app-service'
          container-image-name-updates: 'container=openfido-prod-app-task,tag=$CIRCLE_TAG'
          aws-access-key-id: PROD_AWS_ACCESS_KEY_ID
          aws-secret-access-key: PROD_AWS_SECRET_ACCESS_KEY
