version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
  aws-ecs: circleci/aws-ecs@1.3.0
jobs:
  test:
    docker:
      - image: python:3.8
    environment:
      PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/my-project
    steps:
      - checkout
      - run:
          command: |
            apt-get update -qq
            apt-get install -y pipenv
            pip install virtualenv
      - restore_cache:
          keys:
            - project-pipfile-{{ checksum "Pipfile.lock" }}
      - run:
          command: pipenv install --dev
      - save_cache:
          key: project-pipfile-{{ checksum "Pipfile.lock" }}
          paths:
            - .venv
      - run:
          command: |
            mkdir test-results
            pipenv run invoke test --junit --enforce-percent 100
      - store_test_results:
          path: test-results
      - run:
          command: pipenv run invoke style
      - run:
          command: pipenv run invoke lint --fail-under=9
workflows:
  test_build_and_push:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          requires:
            - test
          tag: "$CIRCLE_BRANCH"
          repo: openfido/dev-app-service
          extra-build-args: "--ssh default"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: 'openfido/dev-app-serviceApp-task'
          cluster-name: 'openfido-dev-ecs-cluster'
          service-name: 'openfido/dev-app_service'
          container-image-name-updates: 'container=openfido/dev-app-serviceApp-task,tag=master'
