version: 2.1
orbs:
  node: circleci/node@2.1.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: latest
      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: Run Lint
          command: |
            npm run lint
      - run:
          name: Build
          command: |
            npm run build
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "staging" ] ; then
              echo Deploy to Staging...
              AWS_ACCESS_KEY_ID="${STAGE_ACCESS_KEY_ID}" AWS_SECRET_ACCESS_KEY="${STAGE_SECRET_ACCESS_KEY}" AWS_REGION="${AWS_REGION}" CF_ID="${STAGE_CF_ID}" S3_BUCKET="${STAGE_S3_URL}" NODE_ENV=staging node ./scripts/deploy.js
              echo Deploy Complete
            elif [ "${CIRCLE_BRANCH}" == "master" ] ; then
              echo Deploy to Production...
              AWS_ACCESS_KEY_ID="${PROD_ACCESS_KEY_ID}" AWS_SECRET_ACCESS_KEY="${PROD_SECRET_ACCESS_KEY}" AWS_REGION="${AWS_REGION}" CF_ID="${PROD_CF_ID}" S3_BUCKET="${PROD_S3_URL}" NODE_ENV=production node ./scripts/deploy.js
              echo Deploy Complete
            fi