version: 2.1

orbs:
  node: circleci/node@2.1.1
  aws-static-site-deploy: realself/aws-static-site-deploy@1.0.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: latest
      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: Run Lint
          command: |
            npm run lint
      - run:
          name: Build
          command: |
            npm run build

workflows:
  dev:
    jobs:
      - build:
          filters:
            branches:
              only: /master/
      - aws-static-site-deploy/copy-site:
          requires:
            - build
          filters:
            branches:
              only: /master/
          to: $STAGE_S3_URL
          from: './build'
          distribution-id: $STAGE_CF_ID
          access-key: $STAGE_ACCESS_KEY_ID
          secret-key: $STAGE_SECRET_ACCESS_KEY

  prod:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)+/
            branches:
              ignore: /.*/
      - aws-static-site-deploy/copy-site:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)+/
            branches:
              ignore: /.*/
          to: $PROD_S3_URL
          from: './build'
          distribution-id: $PROD_CF_ID
          access-key: $PROD_ACCESS_KEY_ID
          secret-key: $PROD_SECRET_ACCESS_KEY