name: Terraform Staging Destroy
on: 
  workflow_dispatch:

jobs:
  docker:
    name: Terraform Staging Destroy
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.1.6
    steps:
      - name: Configure AWS Credentials
        id: config-aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Staging Destroy 
        if: steps.staging-apply.outcome == 'success'
        run: |
          cd deploy/
          terraform init
          terraform workspace select staging 
          terraform destroy -auto-approve