name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Test and Lint
      run: echo "Test and Lint"