
name: Test and Build 

on: 
  push:
    branches: 
      - master
      - features/**
      - dependabot/**
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  docker:
    name: Build and Push
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.1.6
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Terraform
        id: validate
        run:  |
          cd deploy/
          terraform init -backend=false
          terraform validate
          terraform fmt -check


      - name: Build and Push
        if: steps.validate.outcome == 'success'
        id: build
        run: echo "Build and Push docker image"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Staging Plan 
        if: steps.build.outcome == 'success'
        run: |
          cd deploy/
          # pass variable into terraform 
          export TF_VAR_ecr_image_api=$ECR_REPO_BASE_URL
          terraform init
          terraform workspace select staging || terraform workspace new staging
          terraform plan
