
name: Super-Linter

on: 
  push:
    branches: 
      - master
      - features/**
      - dependabot/**
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  docker:
    name: Build and Push
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Validate Terraform
        id: validate
        run: echo "Validate Terraform"

      - name: Build and Push
        if: steps.validate.outcome == 'success'
        id: build
        run: echo "Build and Push docker image"

      - name: Staging Plan 
        if: steps.build.outcome == 'success'
        run: echo "Run Terraform Plan for Staging"