
name: Test and Build 

on: 
  push:
    branches: 
      - master
      - features/**
      - dependabot/**
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  docker:
    name: Build and Push
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:0.12.21
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose -f "deploy/docker-compose.yml" up -d --build

      - name: Validate Terraform
        id: validate
        run: cd deploy/
        run: terraform init -backend=false
        run: terraform validate
        run: terraform fmt -check


      - name: Build and Push
        if: steps.validate.outcome == 'success'
        id: build
        run: echo "Build and Push docker image"

      - name: Staging Plan 
        if: steps.build.outcome == 'success'
        run: echo "Run Terraform Plan for Staging"